name: linters

on:
  pull_request:
    paths:
      - ".github/workflows/linters.yml"
      - "Makefile"
      - "**.js"
      - "**.jsx"
      - ".eslintignore"
      - ".eslintrc.json"
      - "package.json"
      - "yarn.lock"

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Cache the node_modules directory
      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint with ESLint
        run: make eslint

  stylelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Cache the node_modules directory
      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Lint with StyleLint
        run: make stylelint
