name: staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Expo CLI
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Recreate staging .env file
        run: |
          echo "GOOGLE_CLIENT_ID_EXPO=${{ secrets.STAGING_GOOGLE_CLIENT_ID_EXPO }}" >> .env
          echo "GOOGLE_CLIENT_ID_ANDROID=${{ secrets.STAGING_GOOGLE_CLIENT_ID_ANDROID }}" >> .env
          echo "GOOGLE_CLIENT_ID_IOS=${{ secrets.STAGING_GOOGLE_CLIENT_ID_IOS }}" >> .env

      - name: Publish with Expo to default channel
        run: expo publish --non-interactive
