name: staging-build

on:
  workflow_dispatch:
    inputs:
      operating-system:
        description: <ios|android>
        required: true
        default: android

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Build the master branch.
          # https://github.com/actions/checkout#usage
          ref: master

      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Expo CLI
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}

      # Cache the node_modules directory
      - name: Set up node_modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          key: node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Recreate staging .env file
        run: |
          echo "GOOGLE_CLIENT_ID_EXPO=${{ secrets.STAGING_GOOGLE_CLIENT_ID_EXPO }}" >> .env
          echo "GOOGLE_CLIENT_ID_ANDROID=${{ secrets.STAGING_GOOGLE_CLIENT_ID_ANDROID }}" >> .env
          echo "GOOGLE_CLIENT_ID_IOS=${{ secrets.STAGING_GOOGLE_CLIENT_ID_IOS }}" >> .env

      - name: Build the application
        run: sh ./scripts/build.sh staging ${{ github.event.inputs.operating-system }}
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
